// <auto-generated />
namespace OneNightWerewolf.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddGameTimeStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGameTimeStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201308070650264_AddGameTimeStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
